### ISSUE TITLE
2017년 5월_지도 행정동_대선 행정동 매칭 테이블.csv adm_cd 누락

### ISSUE THREAD

**Issue by statkclee** [vuski/admdongkor#1]
adm_cd를 키값으로 사용하려고 봤는데...
2017년 5월_지도 행정동_대선 행정동 매칭 테이블.csv 파일에 adm_cd 가 누락되어 있습니다.

그런데... 20대총선_행정동_매칭_테이블.csv 파일에는 adm_cd가 있는데... 

모든 csv 파일에 adm_cd코드가 있었으면 좋겠습니다.

**Comment by vuski** [comment]
adm_cd 코드는 통계청에서 만드는 것 같습니다. 1년 단위로 공개되는데 2017년  1월1일 이후 것들은 아직 코드가 없습니다. 함부로 부여할 수가 없어 임시로 붙여 놓았고, 그래서 아직 해당 코드가 완벽하지 않기 때문에 표에는 넣어놓지 않았습니다. 대신, 행정구역의 한글 이름이 서로 겹치지 않기 때문에 키값으로 쓰시면 됩니다.

그리고  위와 관련된 내용은..... readme.md 에 이미 적혀 있습니다. ^^

**Comment by statkclee** [comment]
R로 작업하는데 한글 인코딩이 깨져서 geojson을 불러와서 @data 내용을 참조하면 adm_cd, adm_name 한글명이 깨져서 맥에서작업하거나, 리눅스로 올려야하나 고민이 있습니다.

adm_cd가 정확하지 않더라도 주의사항 공지하고 붙여놓는게 더 낫지 않나해서 말씀 올립니다.

**Comment by vuski** [comment]
만약 하시려는 작업이 선거데이터 맵핑이라면, adm_cd 만으로는 선관위의 데이터를 매칭시킬 수 없습니다. 선관위에서 동 이름만으로 데이터를 공개하고 있고, 언급하신 해당 csv로 선관위 동 이름과 제가 올린 지도를 매칭시킬 수 있습니다. 따라서  어떤 방법을 쓰시든지 csv 파일의 한글을 읽어내셔야 합니다. 제가 adm_cd를 굳이 붙이지 않은 것은 그것이 있다고 해도 선관위 데이터를 매칭시키는 과정에서 adm_cd가 불필요하기 때문입니다. 확인해보니 2016년 총선 데이터에는 붙어 있는데요, 여러 작업 중에 남았던 파일을 옮겨온 것이라 붙어 있는 것 같습니다. 허나 2016년 총선 역시 마찬가지 경우라고 생각됩니다.

사용하시는 환경이 윈도우라면 메모장 등에서 파일을 열어서 다른이름으로 저장할 때 인코딩을 변경할 수 있습니다. 현재 인코딩 형식은 UTF-8입니다. 저는 R을 쓰지 못하지만, R에서도 자료를 읽을 때 인코딩을 설정할 수 있지 않을까요....?

허나, statkclee 님이 하시려는 일,  겪고 있는 문제, 이미 알고 계신 부분들을 제가 자세히 이해할 수가 없어, 일단은 요청하신대로 adm_cd를 붙여놓았습니다. 

불필요한 오해가 생길까 하여 설명을 조금 자세히 적어보았습니다.

**Comment by statkclee** [comment]
감사합니다... 유용히 써보겠습니다.
