### ISSUE TITLE
시군구 정보 생성 방법문의

### ISSUE THREAD

**Issue by ksy5662** [vuski/admdongkor#4]
안녕하세요 좋은 정보 공유해주셔서 너무 감사드립니다.
현재 화일은 동정보까지 있는데요..혹시 구정보까지만 있는 geojson 파일이 있는지 문의 드립니다.
shape 화일이 있는데 변환을 이름을 포함해서 할수 있는 방법이나 툴이 있는지 문의드립니다.
미리 감사드립니다.

**Comment by vuski** [comment]
안녕하세요.
웹 상에 해당 방법이 설명된 글이 많을 것 같습니다.  QGIS dissolve 혹은 병합이라고 검색하시면 됩니다.
병합이 잘 이루어지도록 폴리곤 정합성에 신경썼으니, 어렵지 않게 하실 수 있을 것 같습니다.
참고로 구 정보 파일만 필요하시다면, 공공데이터에서 검색해보세요.
